#!/usr/bin/env python
import sys
from rqt_sosvr_controller.my_module import MyPlugin
from rqt_gui.main import Main
plugin = 'rqt_sosvr_controller'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))

